### ISSUE TITLE
library not compiling under linux 64-bit

### ISSUE THREAD

**Issue by johnnrr** [usnistgov/REFPROP-cmake#13] opened 2017-10-26 14:55 UTC
Hi there,

I have version 944 of **Refprop** and want to build a shared library under Linux (Debian 64-bit) to have the Matlab Wrapper.
The _cmake_ routine builds all the fortran files, good so far.
The linker tries then to link the library with **numpy f2py** and gives following console output

![grafik](https://user-images.githubusercontent.com/33105376/32059963-d650b0da-ba6d-11e7-8a05-fd4c25da2c48.png)

Numpy is installed, the test prompt gives the output

![grafik](https://user-images.githubusercontent.com/33105376/32060171-53fc6a9c-ba6e-11e7-97b9-c7f2ebe987ed.png)

Any ideas?

**Comment by johnnrr** [comment] 2017-10-26 14:56
**Here comes a kind of solution**

I tried it with another PC with Ubuntu 16.04
There all fortran files are built, but the linker gives an error

>/usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o: error adding symbols ....
collect2: ld returned 1 exit status

Sorry, the output of the console is not complete, because I cannot repeat the error.

I found a workaround which worked for me here
https://bugs.launchpad.net/ubuntu/+source/gcc-4.4/+bug/640734

Here is the code
`$ cd /usr/lib/gcc/x86_64-linux-gnu/5`
`$ sudo cp crtbeginT.o crtbeginT.orig.o`
`$ sudo cp crtbeginS.o crtbeginT.o`

This worked for me and I got the library.

Good luck and thanks for any help at the first part

**Comment by ianhbell** [comment] 2017-10-26 15:48
I wonder what is up with your computers :)  I've not had any issues with this build system and I've built on a number of machines and platforms.  I'm glad to hear you got it working though I would ideally like to understand why this workaround was necessary.  Are you running more than one version of python?  Did it find the version of python that you think it should be using? That seems somewhat likely to me.  Maybe the python that the subprocess call used was not your system python for some odd reason.

**Comment by ianhbell** [comment] 2017-10-26 15:49
I'm going to make some modifications to the build system to try to force it to use the python that cmake finds.  That might be a bit more reliable.

**Comment by ianhbell** [comment] 2017-10-26 18:54
Ok, I pushed some small changes.  Can you check whether that fixes things?  You'll need to pull and update submodules

**Comment by johnnrr** [comment] 2017-10-26 19:55
Ian,
Did not work on my ubuntu machine:
![grafik](https://user-images.githubusercontent.com/33105376/32073090-2b521e62-ba95-11e7-8ccb-f83b95f6a028.png)

python 2.7.12 and 3.5.2
cmake-version 3.5.1
f2py-version 2
numpy 1.11.0
gcc 5.4.0
ubuntu 16.04 LTS 64-Bit

I can test it at our Debian server tomorrow.

**Comment by ianhbell** [comment] 2017-10-26 20:05
Argh… that’s weird.  Wonder what is going on…  Be interested to hear about other computer…

**Comment by johnnrr** [comment] 2017-10-26 21:58
Here is the log file
[CMakeOutput.log](https://github.com/usnistgov/REFPROP-cmake/files/1420185/CMakeOutput.log)

**Comment by johnnrr** [comment] 2017-10-26 22:17
tried again with the workaround, to see if it still works:
`sudo cp /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o`

![grafik](https://user-images.githubusercontent.com/33105376/32079414-d3c4a258-baaa-11e7-9372-6ff5e4abd8dd.png)

works...

seems like it has something to do with -shared and PIC ("Generate position-independent code (PIC)")

> NOTE: See here: https://bugzilla.redhat.com/show_bug.cgi?id=214465
"crtbeginT.o is not, and should not be PIC. `gcc -shared` should link to crtbeginS.o"

In the workaround I force the code to link to the content of **crtbeginS.o** instead of **crtbeginT.o**.

**Comment by johnnrr** [comment] 2017-10-27 06:45
Hi Ian,

I tested it on the debian server:

![grafik](https://user-images.githubusercontent.com/33105376/32090893-017327f0-baf2-11e7-853d-c018a1c2ceee.png)

.. no success

Here is the system config:
python 2.7.9 (gcc 4.9.2) and 3.4.2 (gcc 4.9.1)
cmake-version 3.0.2
f2py-version 2
numpy 1.8.2
Debian 8.9 (jessie)

and here´s the log
[CMakeOutput.log](https://github.com/usnistgov/REFPROP-cmake/files/1421000/CMakeOutput.log)

**Comment by ianhbell** [comment] 2017-10-27 15:38
On that one you need to do a: git submodule update

and try again because I updated the submodule to make sure that the same python is being used for sure everywhere

**Comment by johnnrr** [comment] 2017-10-27 18:52
I deleted the old repo and made a new clone.

**Comment by ianhbell** [comment] 2017-10-27 19:15
Hmm… I checked and the git repo is pointing to the correct REFPROP-headers commit with this enabled.  Weird.

**Comment by ianhbell** [comment] 2017-10-27 20:00
Can you please provide me with a complete log of your clean, recursive clone?

**Comment by johnnrr** [comment] 2017-10-27 20:25
Do you mean the log of cmake after the clean clone? This is attached some comments before, where I wrote the settings of the seven system.

The only things left before the clone where the folders "fluids" and "mixtures". 
The folder "REFPROP_cmake" had been deleted. Afterwards I copied the old Fortran folder and made the build.

Or do you mean something else?

**Comment by ianhbell** [comment] 2017-10-27 22:08
I mean the log when you execute:

git clone --recursive https://github.com/usnistgov/REFPROP-cmake

I want to make sure that that part is working properly and that you are checking out the correct versions of the code

**Comment by johnnrr** [comment] 2017-10-28 20:55
Ian,
I am on holidays until 6th November. I´ll be back then with news.

**Comment by ianhbell** [comment] 2017-11-03 18:45
I can confirm on my side too now on xubuntu 17.10:

```

Deleting REFPROP.pyf
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginT.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/bin/ld: final link failed: Nonrepresentable section on output

```

________________________________

**Comment by johnnrr** [comment] 2017-11-06 12:38
Today I repeated a clean recursive git clone after deleting the old repo folder.
Here is the log of the console:
![grafik](https://user-images.githubusercontent.com/33105376/32441357-845b83f8-c2f7-11e7-92fa-e7340f8f7931.png)

**Comment by johnnrr** [comment] 2017-11-06 12:43
And again the output of the failed build process

![grafik](https://user-images.githubusercontent.com/33105376/32441499-427b6790-c2f8-11e7-8641-f208290e91b6.png)

**Comment by ianhbell** [comment] 2017-11-06 18:35
Can you try again?  I had tried to “fix” the static linkage to get shared libraries with no other dependencies, but hadn’t tested it on linux.  I think my push might make linux work again

**Comment by johnnrr** [comment] 2017-11-08 11:22
Exactly the same error output on the debian machine as before. Maybe a bug of an old numpy version?
Test on the ubuntu machine follows...

**Comment by ianhbell** [comment] 2017-11-08 17:07
The issue is that the shared library that you end up with has dependencies on libraries on your computer.  I tried to statically link them, but clearly didn't totally succeed.  In any case, it should work now for building on the computer the shared library is to be used.  It may work in other circumstances as well, but linux is very problematic to get the right shared libraries for the standard libraries, more challenging than on windows.

________________________________

**Comment by johnnrr** [comment] 2017-11-10 10:29
Works now on the debian machine too after updating numPy from Version 1.8.2 to 1.12.1.
Everything´s fine now.
Thank you for your support

**Comment by ianhbell** [comment] 2017-11-10 16:25
Good, can you please close this issue then?

________________________________

**Closed** 2017-11-10 22:08 UTC
